export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'  

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const ADD_SERVICE_BEGIN = 'ADD_SERVICE_BEGIN' 
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS'  
export const ADD_SERVICE_ERROR = 'ADD_SERVICE_ERROR'

export const DELETE_SERVICE_BEGIN = 'DELETE_SERVICE_BEGIN'
export const DELETE_SERVICE_SUCCESS =  'DELETE_SERVICE_SUCCESS'  

export const ADD_WORKER_BEGIN = 'ADD_WORKER_BEGIN' 
export const ADD_WORKER_SUCCESS = 'ADD_WORKER_SUCCESS'  
export const ADD_WORKER_ERROR = 'ADD_WORKER_ERROR'

export const UPDATE_WORKER_BEGIN = 'UPDATE_WORKER_BEGIN' 
export const UPDATE_WORKER_SUCCESS = 'UPDATE_WORKER_SUCCESS'  
export const UPDATE_WORKER_ERROR = 'UPDATE_WORKER_ERROR'

export const UPDATE_WORKER_WORKING_HOURS_BEGIN = 'UPDATE_WORKER_WORKING_HOURS_BEGIN' 
export const UPDATE_WORKER_WORKING_HOURS_SUCCESS = 'UPDATE_WORKER_WORKING_HOURS_SUCCESS'  
export const UPDATE_WORKER_WORKING_HOURS_ERROR = 'UPDATE_WORKER_WORKING_HOURS_ERROR'

export const UPDATE_SALON_DATA_BEGIN = 'UPDATE_SALON_DATA_BEGIN' 
export const UPDATE_SALON_DATA_SUCCESS = 'UPDATE_SALON_DATA_SUCCESS'  
export const UPDATE_SALON_DATA_ERROR = 'UPDATE_SALON_DATA_ERROR'

export const UPDATE_SALON_OPENING_HOURS_BEGIN = 'UPDATE_SALON_OPENING_HOURS_BEGIN' 
export const UPDATE_SALON_OPENING_HOURS_SUCCESS = 'UPDATE_SALON_OPENING_HOURS_SUCCESS'  
export const UPDATE_SALON_OPENING_HOURS_ERROR = 'UPDATE_SALON_OPENING_HOURS_ERROR'

export const UPDATE_SALON_GALLERY_BEGIN = 'UPDATE_SALON_GALLERY_BEGIN' 
export const UPDATE_SALON_GALLERY_SUCCESS = 'UPDATE_SALON_GALLERY_SUCCESS'  
export const UPDATE_SALON_GALLERY_ERROR = 'UPDATE_SALON_GALLERY_ERROR'

export const DELETE_SALON_IMG_BEGIN = 'DELETE_SALON_IMG_BEGIN'
export const DELETE_SALON_IMG_SUCCESS =  'DELETE_SALON_IMG_SUCCESS' 

export const ADD_NEW_APPOINTMENT_BEGIN = 'ADD_NEW_APPOINTMENT_BEGIN' 
export const ADD_NEW_APPOINTMENT_SUCCESS = 'ADD_NEW_APPOINTMENT_SUCCESS'  
export const ADD_NEW_APPOINTMENT_ERROR = 'ADD_NEW_APPOINTMENT_ERROR'









